Cloud client
botpress/nlu pull request #63
Opened 2021-07-23 13:47 UTC by michaelmass

2021-07-27 13:11 UTC, spg commented on packages/nlu-client/src/oauth.ts
> +const headerFormatter = (res: any) => 'bearer ' + res.access_token
Maybe prefer template strings (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

2021-07-27 13:12 UTC, spg approved these changes

2021-07-28 14:37 UTC, EFF requested changes
Few code standard to fix, other than that, logic is LGTM

2021-07-28 14:37 UTC, EFF commented on packages/nlu-client/src/oauth.ts
> +interface OauthClientProps {
We also tend to declare types and interface at the top of files as it's much easier to refac when it's time to extract types in dedicated typing files

2021-08-03 15:17 UTC, franklevasseur approved these changes
You'll need to increase the version of `nlu-client` by a patch so I can republish it on npm

2021-08-03 15:20 UTC, merged